name:                rtl
version:             0.1.0.0
github:              "mdko/rtl"
license:             BSD3
author:              "Michael Christensen"
maintainer:          "chmdko@gmail.com"
copyright:           "(c) 2017 Michael Christensen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/mdko/rtl#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  rtl-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rtl

tests:
  rtl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rtl
